# Generated by Django 4.0.3 on 2022-12-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmsoft', '0002_alter_order_o_date_alter_product_p_registerdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_phone_number',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_phone_number',
            field=models.CharField(max_length=200),
        ),
    ]
